name: 'Build and deploy app :)'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
      - name: build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{github.run_number}}
      - name: publish artifacts
        run: dotnet publish --no-restore --no-build --configuration Release --output artifacts/backend src/devschool-ci-test.csproj
  tests:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        include:
          - category: unit
            cmd: devschool-ci-test.dll

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Decompress artifact
        run: >
          tar -I "zstd -d" -xvf ./artifact.zstd --strip-components=2

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run ${{ matrix.category }} tests
        run: dotnet test ${{ matrix.cmd }}
  deploy:
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy-app.yml
    with:
      image_number: ${{ github.run_number }}
    secrets: inherit